name: Actividad02 - PackageNugets

env:
  DOTNET_VERSION: '8.0'

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
          dotnet restore CustomerApp/CustomerApp.sln
          dotnet restore Notifications/Notifications.sln

      - name: Build solutions
        run: |
          dotnet build CustomerApp/CustomerApp.sln --configuration Release --no-restore
          dotnet build Notifications/Notifications.sln --configuration Release --no-restore

      - name: Run unit tests
        run: |
          dotnet test CustomerApp/CustomerApp.Domain.Tests/CustomerApp.Domain.Tests.csproj --configuration Release --logger trx --results-directory CustomerApp/TestResults --no-build
          dotnet test Notifications/Notifications.Domain.Tests/Notifications.Domain.Tests.csproj --configuration Release --logger trx --results-directory Notifications/TestResults --no-build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            CustomerApp/TestResults
            Notifications/TestResults

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Pack nuget packages
        run: |
          # Crear directorio para paquetes
          mkdir -p nuget-packages
          
          dotnet pack CustomerApp/CustomerApp.Domain/CustomerApp.Domain.csproj \
            -c Release \
            -p:PackageVersion=2025.1001.${{ github.run_number }} \
            -p:RepositoryUrl=https://github.com/${{ github.repository }} \
            -p:RepositoryType=git \
            --output ./nuget-packages

          dotnet pack Notifications/Notifications.Domain/Notifications.Domain.csproj \
            -c Release \
            -p:PackageVersion=2025.1001.${{ github.run_number }} \
            -p:RepositoryUrl=https://github.com/${{ github.repository }} \
            -p:RepositoryType=git \
            --output ./nuget-packages

      - name: Configure GitHub NuGet Source
        run: |
          dotnet nuget add source \
            --name github \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: List NuGet sources (debug)
        run: dotnet nuget list source

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push ./nuget-packages/*.nupkg \
            --source github \
            --skip-duplicate \
            --api-key ${{ secrets.GITHUB_TOKEN }}