name: Actividad02 - PackageNuget

env:
  DOTNET_VERSION: '8.0'

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies & Build solutions
        run: |
          dotnet restore CustomerApp/CustomerApp.sln
          dotnet restore Notifications/Notifications.sln
          dotnet build CustomerApp/CustomerApp.sln --configuration Release
          dotnet build Notifications/Notifications.sln --configuration Release

      - name: Run unit tests and collect results (CustomerApp)
        run: |
          dotnet test CustomerApp/CustomerApp.Domain.Tests/CustomerApp.Domain.Tests.csproj --configuration Release --logger trx --results-directory CustomerApp/TestResults

      - name: Run unit tests and collect results (Notifications)
        run: |
          dotnet test Notifications/Notifications.Domain.Tests/Notifications.Domain.Tests.csproj --configuration Release --logger trx --results-directory Notifications/TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            CustomerApp/TestResults
            Notifications/TestResults

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Pack nuget package (CustomerApp.Domain)
        run: |
          dotnet pack CustomerApp/CustomerApp.Domain/CustomerApp.Domain.csproj -c Release \
            -p:PackageVersion=2025.1001.${{ github.run_number }} \
            -p:RepositoryUrl=https://github.com/${{ github.repository }} \
            -p:RepositoryType=git

      - name: Pack nuget package (Notifications.Domain)
        run: |
          dotnet pack Notifications/Notifications.Domain/Notifications.Domain.csproj -c Release \
            -p:PackageVersion=2025.1001.${{ github.run_number }} \
            -p:RepositoryUrl=https://github.com/${{ github.repository }} \
            -p:RepositoryType=git

      - name: nuget sources
        run: dotnet nuget list source

      - name: Push nuget package to GitHub Packages (CustomerApp.Domain)
        run: |
          dotnet nuget push CustomerApp/CustomerApp.Domain/bin/Release/*.nupkg --skip-duplicate --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Push nuget package to GitHub Packages (Notifications.Domain)
        run: |
          dotnet nuget push Notifications/Notifications.Domain/bin/Release/*.nupkg --skip-duplicate --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}